name: Build and push Docker image - alpineer-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          server-id: github

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t mariodaoudvives/alpineer-backend:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push mariodaoudvives/alpineer-backend:${{ github.sha }}
